server:
  port: 8070

spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: admin
    password: admin
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.HSQLDialect
  artemis:
    embedded:
      enabled: false
    mode: native
    host: localhost
    port: 61616
    user: admin
    password: admin